name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:
    branches:
      - main

concurrency:
  group: '${{ github.workflow }}-${{ github.ref_name }}'
  cancel-in-progress: true

jobs:
  ci:
    runs-on: windows-latest
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: 'source'
          fetch-depth: 0

      - name: Test action
        uses: ./source/
        with:
          path: test_dir
